const LanguageKey = {
    SUBMIT_FEEDBACK : Liferay.Language.get("dwtc-submit-feedback-btn"),
    GOOD_RATING : Liferay.Language.get("dwtc-good-rating-number"),
    BAD_RATING : Liferay.Language.get("dwtc-bad-rating-number"),
    EXCELLENT_RATING : Liferay.Language.get("dwtc-excellent-rating-number"),
    WRITE_REVIEW_PLACEHOLDER : Liferay.Language.get("dwtc-write-review-placeholder"),
    RATING_TEXT : Liferay.Language.get("dwtc-rating-text"),
    SHARE_MORE_FEEDBACK : Liferay.Language.get("dwtc-share-more-feedback"),
    ORDER_CREATED_ON : Liferay.Language.get("dwtc-order-created-on"),
    NO_ACTIVE_ORDERS : Liferay.Language.get("dwtc-no-active-orders"),
    NO_PAST_ORDERS : Liferay.Language.get("dwtc-no-past-orders"),
    PAST_ORDER_HEADING : Liferay.Language.get("dwtc-past-orders-heading"),
    ACTIVE_ORDER_HEADING : Liferay.Language.get("dwtc-active-orders-heading"),
    BACK_BUTTON : Liferay.Language.get("dwtc-back-button"),
    SubTotal : Liferay.Language.get("sub-total"),
    OrderTotal : Liferay.Language.get("order-total"),
    TakeAway : Liferay.Language.get("takeaway-option"),
    HomeDelivery : Liferay.Language.get("homedelivery-option"),
    CartPageContinue : Liferay.Language.get("cart-page-continue"),
    PaymentSummary : Liferay.Language.get("payment-summary-heading"),
    ItemSummary : Liferay.Language.get("item-summary-heading"),
    DeliveryCharges : Liferay.Language.get("delivery-charges"),
    VatCharges : Liferay.Language.get("vat-charges"),
    Discout : Liferay.Language.get("discount-applied"),
    PaymentBtn : Liferay.Language.get("payment-btn"),
    CheckoutBtn : Liferay.Language.get("checkout-btn"),
    CouponNotFound : Liferay.Language.get("coupon-not-found"),
    CouponApplied : Liferay.Language.get("coupon-applied"),
    ApplyCouponBtn : Liferay.Language.get("apply-coupon-btn"),
    ViewAllCoupons : Liferay.Language.get("view-all-coupons"),
    SpecialInstruction : Liferay.Language.get("special-instruction"),
    DeleteCoupon : Liferay.Language.get("delete-coupon"),
    DeleteCartItemBtn : Liferay.Language.get("delete-cart-item-btn"),
    NoCartItemExist : Liferay.Language.get("no-cart-item-exist"),
    NoOptionsExist : Liferay.Language.get("no-options-exist"),
    YourSavedAddressHeading : Liferay.Language.get("dwtc-your-saved-address-heading"),
    AddNewAddressButton : Liferay.Language.get("dwtc-add-new-address-btn"),
    NO_ACCOUNT_ADDRESS_FOUND : Liferay.Language.get("dwtc-account-address-found"),
    NO_SHIPPING_ADDRESS_FOUND : Liferay.Language.get("dwtc-no-shipping-address-found"),
    NO_BILLING_ADDRESS_FOUND : Liferay.Language.get("dwtc-no-billing-address-found"),
    STREET: Liferay.Language.get("dwtc-street"),
    SUBURB: Liferay.Language.get("dwtc-suburb"),
    STATE: Liferay.Language.get("dwtc-state"),
    COUNTRY: Liferay.Language.get("dwtc-country"),
    PROCESS_COMPLETED: Liferay.Language.get("dwtc-address-process-completed"),
    CLOSE: Liferay.Language.get("dwtc-close")
}

export default LanguageKey;